// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentIntentReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderNo           string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	ChainType         string                 `protobuf:"bytes,2,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network           string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	ChainId           int64                  `protobuf:"varint,4,opt,name=chainId,proto3" json:"chainId,omitempty"`
	AssetSymbol       string                 `protobuf:"bytes,5,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	AssetAddress      string                 `protobuf:"bytes,6,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	PayerAccount      string                 `protobuf:"bytes,7,opt,name=payerAccount,proto3" json:"payerAccount,omitempty"`
	PayerTokenAccount string                 `protobuf:"bytes,8,opt,name=payerTokenAccount,proto3" json:"payerTokenAccount,omitempty"`
	ReferenceId       string                 `protobuf:"bytes,9,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePaymentIntentReq) Reset() {
	*x = CreatePaymentIntentReq{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentReq) ProtoMessage() {}

func (x *CreatePaymentIntentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreatePaymentIntentReq) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetPayerAccount() string {
	if x != nil {
		return x.PayerAccount
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetPayerTokenAccount() string {
	if x != nil {
		return x.PayerTokenAccount
	}
	return ""
}

func (x *CreatePaymentIntentReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CreatePaymentIntentResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo            string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	OrderNo              string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	ChainType            string                 `protobuf:"bytes,3,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network              string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	ChainId              int64                  `protobuf:"varint,5,opt,name=chainId,proto3" json:"chainId,omitempty"`
	PayMode              string                 `protobuf:"bytes,6,opt,name=payMode,proto3" json:"payMode,omitempty"`
	ReceiverAccount      string                 `protobuf:"bytes,7,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	ReceiverTokenAccount string                 `protobuf:"bytes,8,opt,name=receiverTokenAccount,proto3" json:"receiverTokenAccount,omitempty"`
	AssetAddress         string                 `protobuf:"bytes,9,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	AssetSymbol          string                 `protobuf:"bytes,10,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	AmountExpected       string                 `protobuf:"bytes,11,opt,name=amountExpected,proto3" json:"amountExpected,omitempty"`
	Decimals             int64                  `protobuf:"varint,12,opt,name=decimals,proto3" json:"decimals,omitempty"`
	ReferenceId          string                 `protobuf:"bytes,13,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	ContractAddress      string                 `protobuf:"bytes,14,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Method               string                 `protobuf:"bytes,15,opt,name=method,proto3" json:"method,omitempty"`
	Calldata             string                 `protobuf:"bytes,16,opt,name=calldata,proto3" json:"calldata,omitempty"`
	Value                string                 `protobuf:"bytes,17,opt,name=value,proto3" json:"value,omitempty"`
	SerializedMessage    string                 `protobuf:"bytes,18,opt,name=serializedMessage,proto3" json:"serializedMessage,omitempty"`
	QuoteExpiredAt       int64                  `protobuf:"varint,19,opt,name=quoteExpiredAt,proto3" json:"quoteExpiredAt,omitempty"`
	Status               string                 `protobuf:"bytes,20,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentIntentResp) Reset() {
	*x = CreatePaymentIntentResp{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResp) ProtoMessage() {}

func (x *CreatePaymentIntentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *CreatePaymentIntentResp) GetPayMode() string {
	if x != nil {
		return x.PayMode
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetReceiverAccount() string {
	if x != nil {
		return x.ReceiverAccount
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetReceiverTokenAccount() string {
	if x != nil {
		return x.ReceiverTokenAccount
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetAmountExpected() string {
	if x != nil {
		return x.AmountExpected
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreatePaymentIntentResp) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetCalldata() string {
	if x != nil {
		return x.Calldata
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetSerializedMessage() string {
	if x != nil {
		return x.SerializedMessage
	}
	return ""
}

func (x *CreatePaymentIntentResp) GetQuoteExpiredAt() int64 {
	if x != nil {
		return x.QuoteExpiredAt
	}
	return 0
}

func (x *CreatePaymentIntentResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitTxReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo        string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	TxId             string                 `protobuf:"bytes,2,opt,name=txId,proto3" json:"txId,omitempty"`
	FromAccount      string                 `protobuf:"bytes,3,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	FromTokenAccount string                 `protobuf:"bytes,4,opt,name=fromTokenAccount,proto3" json:"fromTokenAccount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitTxReq) Reset() {
	*x = SubmitTxReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxReq) ProtoMessage() {}

func (x *SubmitTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxReq.ProtoReflect.Descriptor instead.
func (*SubmitTxReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTxReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *SubmitTxReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SubmitTxReq) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *SubmitTxReq) GetFromTokenAccount() string {
	if x != nil {
		return x.FromTokenAccount
	}
	return ""
}

type SubmitTxResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo          string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	TxId               string                 `protobuf:"bytes,2,opt,name=txId,proto3" json:"txId,omitempty"`
	ConfirmationStatus string                 `protobuf:"bytes,3,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitTxResp) Reset() {
	*x = SubmitTxResp{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxResp) ProtoMessage() {}

func (x *SubmitTxResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxResp.ProtoReflect.Descriptor instead.
func (*SubmitTxResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTxResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *SubmitTxResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SubmitTxResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *SubmitTxResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfirmPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentReq) Reset() {
	*x = ConfirmPaymentReq{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentReq) ProtoMessage() {}

func (x *ConfirmPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentReq.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type ConfirmPaymentResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo          string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	TxId               string                 `protobuf:"bytes,2,opt,name=txId,proto3" json:"txId,omitempty"`
	Confirmations      int64                  `protobuf:"varint,3,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	ConfirmationStatus string                 `protobuf:"bytes,4,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	AmountActual       string                 `protobuf:"bytes,5,opt,name=amountActual,proto3" json:"amountActual,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason      string                 `protobuf:"bytes,7,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfirmPaymentResp) Reset() {
	*x = ConfirmPaymentResp{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResp) ProtoMessage() {}

func (x *ConfirmPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResp.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPaymentResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *ConfirmPaymentResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ConfirmPaymentResp) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *ConfirmPaymentResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *ConfirmPaymentResp) GetAmountActual() string {
	if x != nil {
		return x.AmountActual
	}
	return ""
}

func (x *ConfirmPaymentResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConfirmPaymentResp) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type GetPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentReq) Reset() {
	*x = GetPaymentReq{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentReq) ProtoMessage() {}

func (x *GetPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentReq.ProtoReflect.Descriptor instead.
func (*GetPaymentReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentReq) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type GetPaymentResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo            string                 `protobuf:"bytes,1,opt,name=paymentNo,proto3" json:"paymentNo,omitempty"`
	OrderNo              string                 `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	TxId                 string                 `protobuf:"bytes,3,opt,name=txId,proto3" json:"txId,omitempty"`
	ChainType            string                 `protobuf:"bytes,4,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network              string                 `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	ChainId              int64                  `protobuf:"varint,6,opt,name=chainId,proto3" json:"chainId,omitempty"`
	PayerAccount         string                 `protobuf:"bytes,7,opt,name=payerAccount,proto3" json:"payerAccount,omitempty"`
	PayerTokenAccount    string                 `protobuf:"bytes,8,opt,name=payerTokenAccount,proto3" json:"payerTokenAccount,omitempty"`
	ReceiverAccount      string                 `protobuf:"bytes,9,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	ReceiverTokenAccount string                 `protobuf:"bytes,10,opt,name=receiverTokenAccount,proto3" json:"receiverTokenAccount,omitempty"`
	AssetAddress         string                 `protobuf:"bytes,11,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	AssetSymbol          string                 `protobuf:"bytes,12,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	AmountExpected       string                 `protobuf:"bytes,13,opt,name=amountExpected,proto3" json:"amountExpected,omitempty"`
	AmountActual         string                 `protobuf:"bytes,14,opt,name=amountActual,proto3" json:"amountActual,omitempty"`
	Confirmations        int64                  `protobuf:"varint,15,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	ConfirmationStatus   string                 `protobuf:"bytes,16,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	Status               string                 `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason        string                 `protobuf:"bytes,18,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPaymentResp) Reset() {
	*x = GetPaymentResp{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResp) ProtoMessage() {}

func (x *GetPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResp.ProtoReflect.Descriptor instead.
func (*GetPaymentResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentResp) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *GetPaymentResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetPaymentResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GetPaymentResp) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *GetPaymentResp) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetPaymentResp) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetPaymentResp) GetPayerAccount() string {
	if x != nil {
		return x.PayerAccount
	}
	return ""
}

func (x *GetPaymentResp) GetPayerTokenAccount() string {
	if x != nil {
		return x.PayerTokenAccount
	}
	return ""
}

func (x *GetPaymentResp) GetReceiverAccount() string {
	if x != nil {
		return x.ReceiverAccount
	}
	return ""
}

func (x *GetPaymentResp) GetReceiverTokenAccount() string {
	if x != nil {
		return x.ReceiverTokenAccount
	}
	return ""
}

func (x *GetPaymentResp) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *GetPaymentResp) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *GetPaymentResp) GetAmountExpected() string {
	if x != nil {
		return x.AmountExpected
	}
	return ""
}

func (x *GetPaymentResp) GetAmountActual() string {
	if x != nil {
		return x.AmountActual
	}
	return ""
}

func (x *GetPaymentResp) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *GetPaymentResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *GetPaymentResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentResp) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xbe\x02\n" +
	"\x16CreatePaymentIntentReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x1c\n" +
	"\tchainType\x18\x02 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x04 \x01(\x03R\achainId\x12 \n" +
	"\vassetSymbol\x18\x05 \x01(\tR\vassetSymbol\x12\"\n" +
	"\fassetAddress\x18\x06 \x01(\tR\fassetAddress\x12\"\n" +
	"\fpayerAccount\x18\a \x01(\tR\fpayerAccount\x12,\n" +
	"\x11payerTokenAccount\x18\b \x01(\tR\x11payerTokenAccount\x12 \n" +
	"\vreferenceId\x18\t \x01(\tR\vreferenceId\"\xa9\x05\n" +
	"\x17CreatePaymentIntentResp\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x1c\n" +
	"\tchainType\x18\x03 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x05 \x01(\x03R\achainId\x12\x18\n" +
	"\apayMode\x18\x06 \x01(\tR\apayMode\x12(\n" +
	"\x0freceiverAccount\x18\a \x01(\tR\x0freceiverAccount\x122\n" +
	"\x14receiverTokenAccount\x18\b \x01(\tR\x14receiverTokenAccount\x12\"\n" +
	"\fassetAddress\x18\t \x01(\tR\fassetAddress\x12 \n" +
	"\vassetSymbol\x18\n" +
	" \x01(\tR\vassetSymbol\x12&\n" +
	"\x0eamountExpected\x18\v \x01(\tR\x0eamountExpected\x12\x1a\n" +
	"\bdecimals\x18\f \x01(\x03R\bdecimals\x12 \n" +
	"\vreferenceId\x18\r \x01(\tR\vreferenceId\x12(\n" +
	"\x0fcontractAddress\x18\x0e \x01(\tR\x0fcontractAddress\x12\x16\n" +
	"\x06method\x18\x0f \x01(\tR\x06method\x12\x1a\n" +
	"\bcalldata\x18\x10 \x01(\tR\bcalldata\x12\x14\n" +
	"\x05value\x18\x11 \x01(\tR\x05value\x12,\n" +
	"\x11serializedMessage\x18\x12 \x01(\tR\x11serializedMessage\x12&\n" +
	"\x0equoteExpiredAt\x18\x13 \x01(\x03R\x0equoteExpiredAt\x12\x16\n" +
	"\x06status\x18\x14 \x01(\tR\x06status\"\x8d\x01\n" +
	"\vSubmitTxReq\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x12\n" +
	"\x04txId\x18\x02 \x01(\tR\x04txId\x12 \n" +
	"\vfromAccount\x18\x03 \x01(\tR\vfromAccount\x12*\n" +
	"\x10fromTokenAccount\x18\x04 \x01(\tR\x10fromTokenAccount\"\x88\x01\n" +
	"\fSubmitTxResp\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x12\n" +
	"\x04txId\x18\x02 \x01(\tR\x04txId\x12.\n" +
	"\x12confirmationStatus\x18\x03 \x01(\tR\x12confirmationStatus\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"1\n" +
	"\x11ConfirmPaymentReq\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\"\xfe\x01\n" +
	"\x12ConfirmPaymentResp\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x12\n" +
	"\x04txId\x18\x02 \x01(\tR\x04txId\x12$\n" +
	"\rconfirmations\x18\x03 \x01(\x03R\rconfirmations\x12.\n" +
	"\x12confirmationStatus\x18\x04 \x01(\tR\x12confirmationStatus\x12\"\n" +
	"\famountActual\x18\x05 \x01(\tR\famountActual\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\rfailureReason\x18\a \x01(\tR\rfailureReason\"-\n" +
	"\rGetPaymentReq\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\"\x84\x05\n" +
	"\x0eGetPaymentResp\x12\x1c\n" +
	"\tpaymentNo\x18\x01 \x01(\tR\tpaymentNo\x12\x18\n" +
	"\aorderNo\x18\x02 \x01(\tR\aorderNo\x12\x12\n" +
	"\x04txId\x18\x03 \x01(\tR\x04txId\x12\x1c\n" +
	"\tchainType\x18\x04 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x06 \x01(\x03R\achainId\x12\"\n" +
	"\fpayerAccount\x18\a \x01(\tR\fpayerAccount\x12,\n" +
	"\x11payerTokenAccount\x18\b \x01(\tR\x11payerTokenAccount\x12(\n" +
	"\x0freceiverAccount\x18\t \x01(\tR\x0freceiverAccount\x122\n" +
	"\x14receiverTokenAccount\x18\n" +
	" \x01(\tR\x14receiverTokenAccount\x12\"\n" +
	"\fassetAddress\x18\v \x01(\tR\fassetAddress\x12 \n" +
	"\vassetSymbol\x18\f \x01(\tR\vassetSymbol\x12&\n" +
	"\x0eamountExpected\x18\r \x01(\tR\x0eamountExpected\x12\"\n" +
	"\famountActual\x18\x0e \x01(\tR\famountActual\x12$\n" +
	"\rconfirmations\x18\x0f \x01(\x03R\rconfirmations\x12.\n" +
	"\x12confirmationStatus\x18\x10 \x01(\tR\x12confirmationStatus\x12\x16\n" +
	"\x06status\x18\x11 \x01(\tR\x06status\x12$\n" +
	"\rfailureReason\x18\x12 \x01(\tR\rfailureReason2\xa6\x02\n" +
	"\aPayment\x12X\n" +
	"\x13CreatePaymentIntent\x12\x1f.payment.CreatePaymentIntentReq\x1a .payment.CreatePaymentIntentResp\x127\n" +
	"\bSubmitTx\x12\x14.payment.SubmitTxReq\x1a\x15.payment.SubmitTxResp\x12I\n" +
	"\x0eConfirmPayment\x12\x1a.payment.ConfirmPaymentReq\x1a\x1b.payment.ConfirmPaymentResp\x12=\n" +
	"\n" +
	"GetPayment\x12\x16.payment.GetPaymentReq\x1a\x17.payment.GetPaymentRespB\vZ\t./paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(*CreatePaymentIntentReq)(nil),  // 0: payment.CreatePaymentIntentReq
	(*CreatePaymentIntentResp)(nil), // 1: payment.CreatePaymentIntentResp
	(*SubmitTxReq)(nil),             // 2: payment.SubmitTxReq
	(*SubmitTxResp)(nil),            // 3: payment.SubmitTxResp
	(*ConfirmPaymentReq)(nil),       // 4: payment.ConfirmPaymentReq
	(*ConfirmPaymentResp)(nil),      // 5: payment.ConfirmPaymentResp
	(*GetPaymentReq)(nil),           // 6: payment.GetPaymentReq
	(*GetPaymentResp)(nil),          // 7: payment.GetPaymentResp
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.Payment.CreatePaymentIntent:input_type -> payment.CreatePaymentIntentReq
	2, // 1: payment.Payment.SubmitTx:input_type -> payment.SubmitTxReq
	4, // 2: payment.Payment.ConfirmPayment:input_type -> payment.ConfirmPaymentReq
	6, // 3: payment.Payment.GetPayment:input_type -> payment.GetPaymentReq
	1, // 4: payment.Payment.CreatePaymentIntent:output_type -> payment.CreatePaymentIntentResp
	3, // 5: payment.Payment.SubmitTx:output_type -> payment.SubmitTxResp
	5, // 6: payment.Payment.ConfirmPayment:output_type -> payment.ConfirmPaymentResp
	7, // 7: payment.Payment.GetPayment:output_type -> payment.GetPaymentResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
