// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderclient

import (
	"context"

	"order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CloseOrderReq     = order.CloseOrderReq
	CloseOrderResp    = order.CloseOrderResp
	CreateOrderReq    = order.CreateOrderReq
	CreateOrderResp   = order.CreateOrderResp
	GetOrderReq       = order.GetOrderReq
	GetOrderResp      = order.GetOrderResp
	MarkOrderPaidReq  = order.MarkOrderPaidReq
	MarkOrderPaidResp = order.MarkOrderPaidResp

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error)
		CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrder) MarkOrderPaid(ctx context.Context, in *MarkOrderPaidReq, opts ...grpc.CallOption) (*MarkOrderPaidResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.MarkOrderPaid(ctx, in, opts...)
}

func (m *defaultOrder) CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderResp, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CloseOrder(ctx, in, opts...)
}
