// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrderReq struct {
	BizType  string `json:"bizType"`
	BizId    string `json:"bizId"`
	UserId   int64  `json:"userId"`
	Currency string `json:"currency"` // USD/CNY
	Amount   string `json:"amount"`   // fiat amount as decimal string
}

type CreateOrderResp struct {
	OrderNo   string `json:"orderNo"`
	Status    string `json:"status"`
	ExpiredAt int64  `json:"expiredAt"`
}

type CreatePaymentIntentReq struct {
	OrderNo           string `json:"orderNo"`
	ChainType         string `json:"chainType"` // evm / solana
	Network           string `json:"network"`   // mainnet / testnet / devnet
	ChainId           int64  `json:"chainId"`
	AssetSymbol       string `json:"assetSymbol"`  // ETH / USDT / SOL / USDC
	AssetAddress      string `json:"assetAddress"` // contract address or Solana mint, empty for native coin
	PayerAccount      string `json:"payerAccount"`
	PayerTokenAccount string `json:"payerTokenAccount,optional"`
	ReferenceId       string `json:"referenceId,optional"`
}

type CreatePaymentIntentResp struct {
	PaymentNo            string `json:"paymentNo"`
	OrderNo              string `json:"orderNo"`
	ChainType            string `json:"chainType"`
	Network              string `json:"network"`
	ChainId              int64  `json:"chainId"`
	PayMode              string `json:"payMode"` // transfer | contract_call
	ReceiverAccount      string `json:"receiverAccount"`
	ReceiverTokenAccount string `json:"receiverTokenAccount,optional"`
	AssetAddress         string `json:"assetAddress"`
	AssetSymbol          string `json:"assetSymbol"`
	AmountExpected       string `json:"amountExpected"`
	Decimals             int64  `json:"decimals"`
	ReferenceId          string `json:"referenceId,optional"`
	ContractAddress      string `json:"contractAddress,optional"`
	Method               string `json:"method,optional"`
	Calldata             string `json:"calldata,optional"`
	Value                string `json:"value,optional"`
	SerializedMessage    string `json:"serializedMessage,optional"`
	QuoteExpiredAt       int64  `json:"quoteExpiredAt"`
	Status               string `json:"status"`
}

type QueryPaymentResp struct {
	PaymentNo            string `json:"paymentNo"`
	OrderNo              string `json:"orderNo"`
	TxId                 string `json:"txId"`
	ChainType            string `json:"chainType"`
	Network              string `json:"network"`
	ChainId              int64  `json:"chainId"`
	PayerAccount         string `json:"payerAccount,optional"`
	PayerTokenAccount    string `json:"payerTokenAccount,optional"`
	ReceiverAccount      string `json:"receiverAccount,optional"`
	ReceiverTokenAccount string `json:"receiverTokenAccount,optional"`
	AssetAddress         string `json:"assetAddress,optional"`
	AssetSymbol          string `json:"assetSymbol"`
	AmountExpected       string `json:"amountExpected"`
	AmountActual         string `json:"amountActual"`
	Confirmations        int64  `json:"confirmations"`
	ConfirmationStatus   string `json:"confirmationStatus,optional"`
	Status               string `json:"status"`
	FailureReason        string `json:"failureReason,optional"`
}

type SubmitTxReq struct {
	PaymentNo        string `json:"paymentNo"`
	TxId             string `json:"txId"`
	FromAccount      string `json:"fromAccount"`
	FromTokenAccount string `json:"fromTokenAccount,optional"`
}

type SubmitTxResp struct {
	PaymentNo          string `json:"paymentNo"`
	TxId               string `json:"txId"`
	ConfirmationStatus string `json:"confirmationStatus,optional"`
	Status             string `json:"status"`
}
