// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: payment.proto

package paymentclient

import (
	"context"

	"payment/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfirmPaymentReq       = payment.ConfirmPaymentReq
	ConfirmPaymentResp      = payment.ConfirmPaymentResp
	CreatePaymentIntentReq  = payment.CreatePaymentIntentReq
	CreatePaymentIntentResp = payment.CreatePaymentIntentResp
	GetPaymentReq           = payment.GetPaymentReq
	GetPaymentResp          = payment.GetPaymentResp
	SubmitTxReq             = payment.SubmitTxReq
	SubmitTxResp            = payment.SubmitTxResp

	Payment interface {
		CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentReq, opts ...grpc.CallOption) (*CreatePaymentIntentResp, error)
		SubmitTx(ctx context.Context, in *SubmitTxReq, opts ...grpc.CallOption) (*SubmitTxResp, error)
		ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error)
		GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentReq, opts ...grpc.CallOption) (*CreatePaymentIntentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.CreatePaymentIntent(ctx, in, opts...)
}

func (m *defaultPayment) SubmitTx(ctx context.Context, in *SubmitTxReq, opts ...grpc.CallOption) (*SubmitTxResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.SubmitTx(ctx, in, opts...)
}

func (m *defaultPayment) ConfirmPayment(ctx context.Context, in *ConfirmPaymentReq, opts ...grpc.CallOption) (*ConfirmPaymentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.ConfirmPayment(ctx, in, opts...)
}

func (m *defaultPayment) GetPayment(ctx context.Context, in *GetPaymentReq, opts ...grpc.CallOption) (*GetPaymentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.GetPayment(ctx, in, opts...)
}
