// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chain.proto

package server

import (
	"context"

	"chain/chain"
	"chain/internal/logic"
	"chain/internal/svc"
)

type ChainServer struct {
	svcCtx *svc.ServiceContext
	chain.UnimplementedChainServer
}

func NewChainServer(svcCtx *svc.ServiceContext) *ChainServer {
	return &ChainServer{
		svcCtx: svcCtx,
	}
}

func (s *ChainServer) GetTransaction(ctx context.Context, in *chain.GetTransactionReq) (*chain.GetTransactionResp, error) {
	l := logic.NewGetTransactionLogic(ctx, s.svcCtx)
	return l.GetTransaction(in)
}

func (s *ChainServer) GetReceipt(ctx context.Context, in *chain.GetReceiptReq) (*chain.GetReceiptResp, error) {
	l := logic.NewGetReceiptLogic(ctx, s.svcCtx)
	return l.GetReceipt(in)
}

func (s *ChainServer) ParsePayment(ctx context.Context, in *chain.ParsePaymentReq) (*chain.ParsePaymentResp, error) {
	l := logic.NewParsePaymentLogic(ctx, s.svcCtx)
	return l.ParsePayment(in)
}
