// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: chain.proto

package chain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainType     string                 `protobuf:"bytes,1,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	ChainId       int64                  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TxId          string                 `protobuf:"bytes,4,opt,name=txId,proto3" json:"txId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionReq) Reset() {
	*x = GetTransactionReq{}
	mi := &file_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReq) ProtoMessage() {}

func (x *GetTransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReq.ProtoReflect.Descriptor instead.
func (*GetTransactionReq) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionReq) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *GetTransactionReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetTransactionReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetTransactionReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type GetTransactionResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TxId               string                 `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	FromAccount        string                 `protobuf:"bytes,2,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount          string                 `protobuf:"bytes,3,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	FromTokenAccount   string                 `protobuf:"bytes,4,opt,name=fromTokenAccount,proto3" json:"fromTokenAccount,omitempty"`
	ToTokenAccount     string                 `protobuf:"bytes,5,opt,name=toTokenAccount,proto3" json:"toTokenAccount,omitempty"`
	AssetAddress       string                 `protobuf:"bytes,6,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	Amount             string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	BlockNumber        int64                  `protobuf:"varint,8,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Slot               int64                  `protobuf:"varint,9,opt,name=slot,proto3" json:"slot,omitempty"`
	ConfirmationStatus string                 `protobuf:"bytes,10,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	Finalized          bool                   `protobuf:"varint,11,opt,name=finalized,proto3" json:"finalized,omitempty"`
	Found              bool                   `protobuf:"varint,12,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransactionResp) Reset() {
	*x = GetTransactionResp{}
	mi := &file_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResp) ProtoMessage() {}

func (x *GetTransactionResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResp.ProtoReflect.Descriptor instead.
func (*GetTransactionResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GetTransactionResp) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *GetTransactionResp) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *GetTransactionResp) GetFromTokenAccount() string {
	if x != nil {
		return x.FromTokenAccount
	}
	return ""
}

func (x *GetTransactionResp) GetToTokenAccount() string {
	if x != nil {
		return x.ToTokenAccount
	}
	return ""
}

func (x *GetTransactionResp) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *GetTransactionResp) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetTransactionResp) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetTransactionResp) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetTransactionResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *GetTransactionResp) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *GetTransactionResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetReceiptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainType     string                 `protobuf:"bytes,1,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	ChainId       int64                  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TxId          string                 `protobuf:"bytes,4,opt,name=txId,proto3" json:"txId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptReq) Reset() {
	*x = GetReceiptReq{}
	mi := &file_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptReq) ProtoMessage() {}

func (x *GetReceiptReq) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptReq.ProtoReflect.Descriptor instead.
func (*GetReceiptReq) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{2}
}

func (x *GetReceiptReq) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *GetReceiptReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GetReceiptReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetReceiptReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type GetReceiptResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TxId               string                 `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	Status             int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	BlockNumber        int64                  `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Slot               int64                  `protobuf:"varint,4,opt,name=slot,proto3" json:"slot,omitempty"`
	GasUsed            int64                  `protobuf:"varint,5,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	FeeAmount          string                 `protobuf:"bytes,6,opt,name=feeAmount,proto3" json:"feeAmount,omitempty"`
	Logs               []*ChainLog            `protobuf:"bytes,7,rep,name=logs,proto3" json:"logs,omitempty"`
	ConfirmationStatus string                 `protobuf:"bytes,8,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	Finalized          bool                   `protobuf:"varint,9,opt,name=finalized,proto3" json:"finalized,omitempty"`
	Found              bool                   `protobuf:"varint,10,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetReceiptResp) Reset() {
	*x = GetReceiptResp{}
	mi := &file_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptResp) ProtoMessage() {}

func (x *GetReceiptResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptResp.ProtoReflect.Descriptor instead.
func (*GetReceiptResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{3}
}

func (x *GetReceiptResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *GetReceiptResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetReceiptResp) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetReceiptResp) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetReceiptResp) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *GetReceiptResp) GetFeeAmount() string {
	if x != nil {
		return x.FeeAmount
	}
	return ""
}

func (x *GetReceiptResp) GetLogs() []*ChainLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetReceiptResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *GetReceiptResp) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *GetReceiptResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ChainLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	LogIndex      int64                  `protobuf:"varint,4,opt,name=logIndex,proto3" json:"logIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainLog) Reset() {
	*x = ChainLog{}
	mi := &file_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainLog) ProtoMessage() {}

func (x *ChainLog) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainLog.ProtoReflect.Descriptor instead.
func (*ChainLog) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{4}
}

func (x *ChainLog) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ChainLog) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ChainLog) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ChainLog) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type ParsePaymentReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChainType            string                 `protobuf:"bytes,1,opt,name=chainType,proto3" json:"chainType,omitempty"`
	Network              string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	ChainId              int64                  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	TxId                 string                 `protobuf:"bytes,4,opt,name=txId,proto3" json:"txId,omitempty"`
	ReceiverAccount      string                 `protobuf:"bytes,5,opt,name=receiverAccount,proto3" json:"receiverAccount,omitempty"`
	ReceiverTokenAccount string                 `protobuf:"bytes,6,opt,name=receiverTokenAccount,proto3" json:"receiverTokenAccount,omitempty"`
	AssetAddress         string                 `protobuf:"bytes,7,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	ExpectedAmount       string                 `protobuf:"bytes,8,opt,name=expectedAmount,proto3" json:"expectedAmount,omitempty"`
	ReferenceId          string                 `protobuf:"bytes,9,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParsePaymentReq) Reset() {
	*x = ParsePaymentReq{}
	mi := &file_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsePaymentReq) ProtoMessage() {}

func (x *ParsePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsePaymentReq.ProtoReflect.Descriptor instead.
func (*ParsePaymentReq) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{5}
}

func (x *ParsePaymentReq) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *ParsePaymentReq) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ParsePaymentReq) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ParsePaymentReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ParsePaymentReq) GetReceiverAccount() string {
	if x != nil {
		return x.ReceiverAccount
	}
	return ""
}

func (x *ParsePaymentReq) GetReceiverTokenAccount() string {
	if x != nil {
		return x.ReceiverTokenAccount
	}
	return ""
}

func (x *ParsePaymentReq) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *ParsePaymentReq) GetExpectedAmount() string {
	if x != nil {
		return x.ExpectedAmount
	}
	return ""
}

func (x *ParsePaymentReq) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ParsePaymentResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Matched            bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	FromAccount        string                 `protobuf:"bytes,2,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount          string                 `protobuf:"bytes,3,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	FromTokenAccount   string                 `protobuf:"bytes,4,opt,name=fromTokenAccount,proto3" json:"fromTokenAccount,omitempty"`
	ToTokenAccount     string                 `protobuf:"bytes,5,opt,name=toTokenAccount,proto3" json:"toTokenAccount,omitempty"`
	AssetAddress       string                 `protobuf:"bytes,6,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	AmountActual       string                 `protobuf:"bytes,7,opt,name=amountActual,proto3" json:"amountActual,omitempty"`
	BlockNumber        int64                  `protobuf:"varint,8,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Slot               int64                  `protobuf:"varint,9,opt,name=slot,proto3" json:"slot,omitempty"`
	Confirmations      int64                  `protobuf:"varint,10,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	ConfirmationStatus string                 `protobuf:"bytes,11,opt,name=confirmationStatus,proto3" json:"confirmationStatus,omitempty"`
	Finalized          bool                   `protobuf:"varint,12,opt,name=finalized,proto3" json:"finalized,omitempty"`
	MatchReason        string                 `protobuf:"bytes,13,opt,name=matchReason,proto3" json:"matchReason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ParsePaymentResp) Reset() {
	*x = ParsePaymentResp{}
	mi := &file_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsePaymentResp) ProtoMessage() {}

func (x *ParsePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsePaymentResp.ProtoReflect.Descriptor instead.
func (*ParsePaymentResp) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{6}
}

func (x *ParsePaymentResp) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ParsePaymentResp) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *ParsePaymentResp) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *ParsePaymentResp) GetFromTokenAccount() string {
	if x != nil {
		return x.FromTokenAccount
	}
	return ""
}

func (x *ParsePaymentResp) GetToTokenAccount() string {
	if x != nil {
		return x.ToTokenAccount
	}
	return ""
}

func (x *ParsePaymentResp) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *ParsePaymentResp) GetAmountActual() string {
	if x != nil {
		return x.AmountActual
	}
	return ""
}

func (x *ParsePaymentResp) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ParsePaymentResp) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ParsePaymentResp) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *ParsePaymentResp) GetConfirmationStatus() string {
	if x != nil {
		return x.ConfirmationStatus
	}
	return ""
}

func (x *ParsePaymentResp) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *ParsePaymentResp) GetMatchReason() string {
	if x != nil {
		return x.MatchReason
	}
	return ""
}

var File_chain_proto protoreflect.FileDescriptor

const file_chain_proto_rawDesc = "" +
	"\n" +
	"\vchain.proto\x12\x05chain\"y\n" +
	"\x11GetTransactionReq\x12\x1c\n" +
	"\tchainType\x18\x01 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x03 \x01(\x03R\achainId\x12\x12\n" +
	"\x04txId\x18\x04 \x01(\tR\x04txId\"\x92\x03\n" +
	"\x12GetTransactionResp\x12\x12\n" +
	"\x04txId\x18\x01 \x01(\tR\x04txId\x12 \n" +
	"\vfromAccount\x18\x02 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x03 \x01(\tR\ttoAccount\x12*\n" +
	"\x10fromTokenAccount\x18\x04 \x01(\tR\x10fromTokenAccount\x12&\n" +
	"\x0etoTokenAccount\x18\x05 \x01(\tR\x0etoTokenAccount\x12\"\n" +
	"\fassetAddress\x18\x06 \x01(\tR\fassetAddress\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12 \n" +
	"\vblockNumber\x18\b \x01(\x03R\vblockNumber\x12\x12\n" +
	"\x04slot\x18\t \x01(\x03R\x04slot\x12.\n" +
	"\x12confirmationStatus\x18\n" +
	" \x01(\tR\x12confirmationStatus\x12\x1c\n" +
	"\tfinalized\x18\v \x01(\bR\tfinalized\x12\x14\n" +
	"\x05found\x18\f \x01(\bR\x05found\"u\n" +
	"\rGetReceiptReq\x12\x1c\n" +
	"\tchainType\x18\x01 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x03 \x01(\x03R\achainId\x12\x12\n" +
	"\x04txId\x18\x04 \x01(\tR\x04txId\"\xb3\x02\n" +
	"\x0eGetReceiptResp\x12\x12\n" +
	"\x04txId\x18\x01 \x01(\tR\x04txId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12 \n" +
	"\vblockNumber\x18\x03 \x01(\x03R\vblockNumber\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\x03R\x04slot\x12\x18\n" +
	"\agasUsed\x18\x05 \x01(\x03R\agasUsed\x12\x1c\n" +
	"\tfeeAmount\x18\x06 \x01(\tR\tfeeAmount\x12#\n" +
	"\x04logs\x18\a \x03(\v2\x0f.chain.ChainLogR\x04logs\x12.\n" +
	"\x12confirmationStatus\x18\b \x01(\tR\x12confirmationStatus\x12\x1c\n" +
	"\tfinalized\x18\t \x01(\bR\tfinalized\x12\x14\n" +
	"\x05found\x18\n" +
	" \x01(\bR\x05found\"l\n" +
	"\bChainLog\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\blogIndex\x18\x04 \x01(\x03R\blogIndex\"\xc3\x02\n" +
	"\x0fParsePaymentReq\x12\x1c\n" +
	"\tchainType\x18\x01 \x01(\tR\tchainType\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x18\n" +
	"\achainId\x18\x03 \x01(\x03R\achainId\x12\x12\n" +
	"\x04txId\x18\x04 \x01(\tR\x04txId\x12(\n" +
	"\x0freceiverAccount\x18\x05 \x01(\tR\x0freceiverAccount\x122\n" +
	"\x14receiverTokenAccount\x18\x06 \x01(\tR\x14receiverTokenAccount\x12\"\n" +
	"\fassetAddress\x18\a \x01(\tR\fassetAddress\x12&\n" +
	"\x0eexpectedAmount\x18\b \x01(\tR\x0eexpectedAmount\x12 \n" +
	"\vreferenceId\x18\t \x01(\tR\vreferenceId\"\xd4\x03\n" +
	"\x10ParsePaymentResp\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12 \n" +
	"\vfromAccount\x18\x02 \x01(\tR\vfromAccount\x12\x1c\n" +
	"\ttoAccount\x18\x03 \x01(\tR\ttoAccount\x12*\n" +
	"\x10fromTokenAccount\x18\x04 \x01(\tR\x10fromTokenAccount\x12&\n" +
	"\x0etoTokenAccount\x18\x05 \x01(\tR\x0etoTokenAccount\x12\"\n" +
	"\fassetAddress\x18\x06 \x01(\tR\fassetAddress\x12\"\n" +
	"\famountActual\x18\a \x01(\tR\famountActual\x12 \n" +
	"\vblockNumber\x18\b \x01(\x03R\vblockNumber\x12\x12\n" +
	"\x04slot\x18\t \x01(\x03R\x04slot\x12$\n" +
	"\rconfirmations\x18\n" +
	" \x01(\x03R\rconfirmations\x12.\n" +
	"\x12confirmationStatus\x18\v \x01(\tR\x12confirmationStatus\x12\x1c\n" +
	"\tfinalized\x18\f \x01(\bR\tfinalized\x12 \n" +
	"\vmatchReason\x18\r \x01(\tR\vmatchReason2\xca\x01\n" +
	"\x05Chain\x12E\n" +
	"\x0eGetTransaction\x12\x18.chain.GetTransactionReq\x1a\x19.chain.GetTransactionResp\x129\n" +
	"\n" +
	"GetReceipt\x12\x14.chain.GetReceiptReq\x1a\x15.chain.GetReceiptResp\x12?\n" +
	"\fParsePayment\x12\x16.chain.ParsePaymentReq\x1a\x17.chain.ParsePaymentRespB\tZ\a./chainb\x06proto3"

var (
	file_chain_proto_rawDescOnce sync.Once
	file_chain_proto_rawDescData []byte
)

func file_chain_proto_rawDescGZIP() []byte {
	file_chain_proto_rawDescOnce.Do(func() {
		file_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)))
	})
	return file_chain_proto_rawDescData
}

var file_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chain_proto_goTypes = []any{
	(*GetTransactionReq)(nil),  // 0: chain.GetTransactionReq
	(*GetTransactionResp)(nil), // 1: chain.GetTransactionResp
	(*GetReceiptReq)(nil),      // 2: chain.GetReceiptReq
	(*GetReceiptResp)(nil),     // 3: chain.GetReceiptResp
	(*ChainLog)(nil),           // 4: chain.ChainLog
	(*ParsePaymentReq)(nil),    // 5: chain.ParsePaymentReq
	(*ParsePaymentResp)(nil),   // 6: chain.ParsePaymentResp
}
var file_chain_proto_depIdxs = []int32{
	4, // 0: chain.GetReceiptResp.logs:type_name -> chain.ChainLog
	0, // 1: chain.Chain.GetTransaction:input_type -> chain.GetTransactionReq
	2, // 2: chain.Chain.GetReceipt:input_type -> chain.GetReceiptReq
	5, // 3: chain.Chain.ParsePayment:input_type -> chain.ParsePaymentReq
	1, // 4: chain.Chain.GetTransaction:output_type -> chain.GetTransactionResp
	3, // 5: chain.Chain.GetReceipt:output_type -> chain.GetReceiptResp
	6, // 6: chain.Chain.ParsePayment:output_type -> chain.ParsePaymentResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chain_proto_init() }
func file_chain_proto_init() {
	if File_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_proto_goTypes,
		DependencyIndexes: file_chain_proto_depIdxs,
		MessageInfos:      file_chain_proto_msgTypes,
	}.Build()
	File_chain_proto = out.File
	file_chain_proto_goTypes = nil
	file_chain_proto_depIdxs = nil
}
