// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package ledgerclient

import (
	"context"

	"ledger/ledger"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = ledger.Request
	Response = ledger.Response

	Ledger interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultLedger struct {
		cli zrpc.Client
	}
)

func NewLedger(cli zrpc.Client) Ledger {
	return &defaultLedger{
		cli: cli,
	}
}

func (m *defaultLedger) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := ledger.NewLedgerClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
