// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package ledgerclient

import (
	"context"

	"ledger/ledger"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateEntryReq  = ledger.CreateEntryReq
	CreateEntryResp = ledger.CreateEntryResp
	GetEntryReq     = ledger.GetEntryReq
	GetEntryResp    = ledger.GetEntryResp

	Ledger interface {
		CreateEntry(ctx context.Context, in *CreateEntryReq, opts ...grpc.CallOption) (*CreateEntryResp, error)
		GetEntry(ctx context.Context, in *GetEntryReq, opts ...grpc.CallOption) (*GetEntryResp, error)
	}

	defaultLedger struct {
		cli zrpc.Client
	}
)

func NewLedger(cli zrpc.Client) Ledger {
	return &defaultLedger{
		cli: cli,
	}
}

func (m *defaultLedger) CreateEntry(ctx context.Context, in *CreateEntryReq, opts ...grpc.CallOption) (*CreateEntryResp, error) {
	client := ledger.NewLedgerClient(m.cli.Conn())
	return client.CreateEntry(ctx, in, opts...)
}

func (m *defaultLedger) GetEntry(ctx context.Context, in *GetEntryReq, opts ...grpc.CallOption) (*GetEntryResp, error) {
	client := ledger.NewLedgerClient(m.cli.Conn())
	return client.GetEntry(ctx, in, opts...)
}
