// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: chain.proto

package chainclient

import (
	"context"

	"chain/chain"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChainLog           = chain.ChainLog
	GetReceiptReq      = chain.GetReceiptReq
	GetReceiptResp     = chain.GetReceiptResp
	GetTransactionReq  = chain.GetTransactionReq
	GetTransactionResp = chain.GetTransactionResp
	ParsePaymentReq    = chain.ParsePaymentReq
	ParsePaymentResp   = chain.ParsePaymentResp

	Chain interface {
		GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error)
		GetReceipt(ctx context.Context, in *GetReceiptReq, opts ...grpc.CallOption) (*GetReceiptResp, error)
		ParsePayment(ctx context.Context, in *ParsePaymentReq, opts ...grpc.CallOption) (*ParsePaymentResp, error)
	}

	defaultChain struct {
		cli zrpc.Client
	}
)

func NewChain(cli zrpc.Client) Chain {
	return &defaultChain{
		cli: cli,
	}
}

func (m *defaultChain) GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error) {
	client := chain.NewChainClient(m.cli.Conn())
	return client.GetTransaction(ctx, in, opts...)
}

func (m *defaultChain) GetReceipt(ctx context.Context, in *GetReceiptReq, opts ...grpc.CallOption) (*GetReceiptResp, error) {
	client := chain.NewChainClient(m.cli.Conn())
	return client.GetReceipt(ctx, in, opts...)
}

func (m *defaultChain) ParsePayment(ctx context.Context, in *ParsePaymentReq, opts ...grpc.CallOption) (*ParsePaymentResp, error) {
	client := chain.NewChainClient(m.cli.Conn())
	return client.ParsePayment(ctx, in, opts...)
}
