// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: payment.proto

package server

import (
	"context"

	"payment/internal/logic"
	"payment/internal/svc"
	"payment/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) CreatePaymentIntent(ctx context.Context, in *payment.CreatePaymentIntentReq) (*payment.CreatePaymentIntentResp, error) {
	l := logic.NewCreatePaymentIntentLogic(ctx, s.svcCtx)
	return l.CreatePaymentIntent(in)
}

func (s *PaymentServer) SubmitTx(ctx context.Context, in *payment.SubmitTxReq) (*payment.SubmitTxResp, error) {
	l := logic.NewSubmitTxLogic(ctx, s.svcCtx)
	return l.SubmitTx(in)
}

func (s *PaymentServer) ConfirmPayment(ctx context.Context, in *payment.ConfirmPaymentReq) (*payment.ConfirmPaymentResp, error) {
	l := logic.NewConfirmPaymentLogic(ctx, s.svcCtx)
	return l.ConfirmPayment(in)
}

func (s *PaymentServer) GetPayment(ctx context.Context, in *payment.GetPaymentReq) (*payment.GetPaymentResp, error) {
	l := logic.NewGetPaymentLogic(ctx, s.svcCtx)
	return l.GetPayment(in)
}
