// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	trade "trade/internal/handler/trade"
	"trade/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建业务订单
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: trade.CreateOrderHandler(serverCtx),
			},
			{
				// 查询支付状态
				Method:  http.MethodGet,
				Path:    "/payments/:paymentNo",
				Handler: trade.QueryPaymentHandler(serverCtx),
			},
			{
				// 创建支付意图
				Method:  http.MethodPost,
				Path:    "/payments/intents",
				Handler: trade.CreatePaymentIntentHandler(serverCtx),
			},
			{
				// 前端提交链上交易ID
				Method:  http.MethodPost,
				Path:    "/payments/submit-tx",
				Handler: trade.SubmitTxHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/trade"),
	)
}
