// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package server

import (
	"context"

	"ledger/internal/logic"
	"ledger/internal/svc"
	"ledger/ledger"
)

type LedgerServer struct {
	svcCtx *svc.ServiceContext
	ledger.UnimplementedLedgerServer
}

func NewLedgerServer(svcCtx *svc.ServiceContext) *LedgerServer {
	return &LedgerServer{
		svcCtx: svcCtx,
	}
}

func (s *LedgerServer) CreateEntry(ctx context.Context, in *ledger.CreateEntryReq) (*ledger.CreateEntryResp, error) {
	l := logic.NewCreateEntryLogic(ctx, s.svcCtx)
	return l.CreateEntry(in)
}

func (s *LedgerServer) GetEntry(ctx context.Context, in *ledger.GetEntryReq) (*ledger.GetEntryResp, error) {
	l := logic.NewGetEntryLogic(ctx, s.svcCtx)
	return l.GetEntry(in)
}
