// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package server

import (
	"context"

	"ledger/internal/logic"
	"ledger/internal/svc"
	"ledger/ledger"
)

type LedgerServer struct {
	svcCtx *svc.ServiceContext
	ledger.UnimplementedLedgerServer
}

func NewLedgerServer(svcCtx *svc.ServiceContext) *LedgerServer {
	return &LedgerServer{
		svcCtx: svcCtx,
	}
}

func (s *LedgerServer) Ping(ctx context.Context, in *ledger.Request) (*ledger.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
